services:
  - type: web
    name: spotify-clone-api-hammad
    runtime: node
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/v1/health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://spotify-clone-web-hammad.onrender.com
      - key: MONGO_URI
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: spotify-clone-web-hammad
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    envVars:
      - key: VITE_API_URL
        value: https://spotify-clone-api-hammad.onrender.com/api/v1
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
